const items = [
   {
      id: 1,
      name: "White Pasta",
      type: "Pasta",
      stock: 7,
      price: 33.19,
      image: "",
   },
   {
      id: 2,
      name: "Cinnamon Rolls",
      type: "Desserts",
      stock: 76,
      price: 10.95,
      image: "",
   },
   {
      id: 3,
      name: "Tuna can",
      type: "Seafood",
      stock: 97,
      price: 69.74,
      image: "",
   },
   {
      id: 4,
      name: "Sea Salt",
      type: "Condiments",
      stock: 27,
      price: 61.45,
      image: "",
   },
   {
      id: 5,
      name: "Brown Sugar",
      type: "Condiments",
      stock: 32,
      price: 33.96,
      image: "",
   },
   {
      id: 6,
      name: "Green Apples",
      type: "Fruits and Vegetables",
      stock: 11,
      price: 2.56,
      image: "",
   },
   {
      id: 7,
      name: "Corn",
      type: "Fruits and Vegetables",
      stock: 36,
      price: 90.74,
      image: "",
   },
   {
      id: 8,
      name: "Scallops",
      type: "Seafood",
      stock: 87,
      price: 99.61,
      image: "",
   },
   {
      id: 9,
      name: "Red Tea",
      type: "Coffee and Tea",
      stock: 33,
      price: 97.63,
      image: "",
   },
   {
      id: 10,
      name: "Red Wine",
      type: "Alcoholic Beverages",
      stock: 65,
      price: 89.47,
      image: "",
   },
   {
      id: 11,
      name: "Kidney Beans",
      type: "Beans",
      stock: 46,
      price: 73.7,
      image: "",
   },
   {
      id: 12,
      name: "Twix chocolate bar",
      type: "Desserts",
      stock: 52,
      price: 41.02,
      image: "",
   },
   {
      id: 13,
      name: "Roasted Chicken",
      type: "Meats",
      stock: 24,
      price: 63.01,
      image: "",
   },
];

module.exports = items